apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  selector:
    run: my-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30007
